package recommendations

const (
	UnitID                     = "unitID"
	SchoolName                 = "school"
	City                       = "city"
	State                      = "state"
	SchoolSetting              = "setting"
	SchoolType                 = "schoolType"
	SchoolURL                  = "url"
	CostInStateOnCampus        = "costInStateOnCampus"
	CostOutStateOnCampus       = "costOutStateOnCampus"
	AcceptanceRate             = "acceptanceRate"
	Act                        = "act"
	Sat                        = "sat"
	IndianOrNative             = "indianOrNative"
	AsianOrPacific             = "asianOrPacific"
	Black                      = "black"
	Hispanic                   = "hispanic"
	White                      = "white"
	International              = "international"
	Multi                      = "multi"
	Unknown                    = "unknown"
	PctStudentBodyFemale       = "female"
	ParentalIncomeTopTenPct    = "parentalIncomeTopTenPct"
	ParentalIncomeTopEightyPct = "parentalIncomeTopEightyPct"
	MedianEarningsAt34         = "medianEarningsAt34"
	StudentPopulation          = "studentPopulation"
	ReligiousAffiliation       = "religiousAffiliation"
	PctWithDisability          = "pctWithDisability"
	LessThan3PCTDisability     = "lessThan3PCTDisability"
	CompanyData                = "AcademicAnalytics"
	IpedsData                  = "dbo"
	IDConversion               = "super_opeids_master"
	MobilityRateTwo            = "mobilityRate_Table2"
	Admissions                 = "ADM2018"
	Diversity                  = "DRVEF2018"
	Cost                       = "DRVIC2018"
	IC                         = "IC2018"
)
